"""initial

Revision ID: 8388ea9dee87
Revises: 
Create Date: 2026-09-21 00:26:28.700981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8388ea9dee87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingesteddocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_hash', name='uq_ingesteddocument_user_file_hash')
    )
    op.create_index(op.f('ix_ingesteddocument_document_id'), 'ingesteddocument', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingesteddocument_file_hash'), 'ingesteddocument', ['file_hash'], unique=False)
    op.create_index(op.f('ix_ingesteddocument_filename'), 'ingesteddocument', ['filename'], unique=False)
    op.create_index(op.f('ix_ingesteddocument_session_id'), 'ingesteddocument', ['session_id'], unique=False)
    op.create_index(op.f('ix_ingesteddocument_user_id'), 'ingesteddocument', ['user_id'], unique=False)
    op.create_table('usermemory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermemory_user_id'), 'usermemory', ['user_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chatsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_session_id'), 'chatmessage', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatmessage_session_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_usermemory_user_id'), table_name='usermemory')
    op.drop_table('usermemory')
    op.drop_index(op.f('ix_ingesteddocument_user_id'), table_name='ingesteddocument')
    op.drop_index(op.f('ix_ingesteddocument_session_id'), table_name='ingesteddocument')
    op.drop_index(op.f('ix_ingesteddocument_filename'), table_name='ingesteddocument')
    op.drop_index(op.f('ix_ingesteddocument_file_hash'), table_name='ingesteddocument')
    op.drop_index(op.f('ix_ingesteddocument_document_id'), table_name='ingesteddocument')
    op.drop_table('ingesteddocument')
    op.drop_table('chatsession')
    # ### end Alembic commands ###
